spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/456789?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

razorpay.api.key=rzp_test_E1VHn4r8R09Rak
razorpay.api.secret=6TLrS5L5z2YkBguOmXq3EIns

